appName: cartservice
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
appVersion: v0.10.2
appReplicas: 2
containerPort: 7070
containerEnvVars: 
- name: PORT
  value: "7070"
- name: REDIS_ADDR
  value: "redis-cart:6379"

servicePort: 7070