appName: currencyservice
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
appVersion: v0.10.2
appReplicas: 2
containerPort: 7000
containerEnvVars: 
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7000